/**
 * scripts/personas.js
 *
 * Persona definitions for the reflection simulator.
 * Each persona represents a different user archetype with distinct
 * goals, tendencies, and journaling patterns.
 *
 * Each persona includes:
 *   - dailyEventBank: 30+ specific things that could happen on a given day (drawn randomly each run)
 *   - recurringBlockers: blocker tags matching the blocker_tags field in the DB
 *   - recurringStrengths: strength patterns that appear with realistic frequency
 */

export const PERSONAS = {
  ambitious_but_inconsistent: {
    name: 'Alex',
    description:
      "Building Stackline — a tool for freelancers to track client retainers and invoice automatically. Strong vision but struggles with follow-through. Makes big commitments, executes maybe 60% of them. Tends to blame external factors when things slip. Genuinely motivated but distracted by shiny new ideas. Lives alone in a studio apartment, has a close friend named Dom who keeps suggesting 'pivot ideas', and a gym habit he keeps meaning to restart.",
    profile: {
      display_name: 'Alex',
      big_goal: 'Get Stackline to 20 paying customers by end of Q2',
      why: "I want to prove I can build something real and stop talking about it",
      future_self: "In a year I'm running a profitable product and don't need to freelance anymore",
      identity_statement: "I'm someone who builds things that matter",
      life_areas: ['work', 'fitness', 'relationships'],
      blockers: ['perfectionism', 'distraction', 'fear_of_shipping'],
      goals: [
        {
          title: 'Get Stackline to 20 paying customers by end of Q2',
          why_it_matters: 'I want to prove I can build something real and stop talking about it',
          category: 'work',
        },
        {
          title: 'Restart a consistent gym habit — 3x per week',
          why_it_matters: "I feel better when I move and I've let it slip for too long",
          category: 'fitness',
        },
        {
          title: 'Stop ghosting my friends — reach out to at least one person each week',
          why_it_matters: "I've been so heads-down on Stackline that I'm losing touch with people who matter",
          category: 'relationships',
        },
      ],
    },
    recurringBlockers: ['distraction', 'perfectionism', 'fear_of_shipping', 'scope_creep'],
    recurringStrengths: ['ships_when_pushed', 'strong_product_vision'],
    dailyEventBank: [
      "Got a reply from a cold email prospect — Marcus, a freelance copywriter — felt like it could actually go somewhere",
      "Spent 90 minutes building the wrong feature and only realized it when Dom pointed it out on a call",
      "Skipped the gym again — 4th day in a row, told myself tomorrow for sure",
      "Had a really encouraging feedback call with a potential user named Rachel who does freelance UX work",
      "Pushed a new build of Stackline at 11pm, felt good but completely drained",
      "Distracted by a YouTube rabbit hole about growth hacking for 2 hours instead of writing copy",
      "Finally wrote the landing page headline after 3 days of avoiding it — it's not perfect but it's something",
      "A competitor called RetainerHQ just launched on ProductHunt — spent way too long comparing their features",
      "Got a genuine compliment from Dom about Stackline's new dashboard design",
      "Skipped reflection yesterday and felt guilty about it all day today",
      "Almost finished the onboarding flow but got stuck on an edge case with invoice currency formatting",
      "Jumped into building an API integration that isn't in the MVP scope because it 'felt important'",
      "Had a call with a potential beta user named Priya who asked exactly the right questions — felt validating",
      "Saw another indie hacker tweet about hitting $10k MRR and felt a weird mix of inspired and behind",
      "Spent the whole afternoon on the pricing page and still don't feel sure about it",
      "Deleted and rewrote the welcome email sequence three times — perfectionism hitting hard",
      "Got 3 signups overnight from a Reddit post Dom shared — excited but also scared now it's real",
      "Cancelled gym again to finish a feature, told myself it's temporary",
      "Had a great 45-minute focus session in the morning, then lost the rest of the day to Slack and Twitter",
      "Dom suggested pivoting Stackline to target agencies instead of solo freelancers — spent hours thinking about it instead of building",
      "Woke up anxious about whether anyone will actually pay for this",
      "Finished the Stripe integration — the biggest technical lift so far — felt genuinely proud",
      "Sent the first cold outreach batch to 20 freelancers on LinkedIn, haven't checked replies yet",
      "Had a long dinner with Rachel who gave brutally honest feedback about the onboarding — hard to hear but probably right",
      "Wrote a short Twitter thread about why I'm building Stackline — got 12 likes, felt underwhelming",
      "Stayed up until 2am fixing a bug that turned out to be a typo — the lost time stings",
      "Blocked 3 hours for deep work and actually used all 3 — this almost never happens",
      "Got a message from a Stackline beta user saying they saved an hour on their last invoice — first real user love",
      "Realized I've been avoiding reaching out to a specific group of potential users because I'm scared of rejection",
      "Ate lunch at my desk for the 7th day in a row — starting to feel the walls closing in",
      "Opened the analytics dashboard and the numbers are flatter than I expected — tried not to spiral",
      "Had a spontaneous brainstorm with Dom that actually produced two solid product ideas I want to explore",
    ],
    tendencies: {
      wins: "Usually has 1-2 real wins but undersells them. Sometimes pivots to talking about what didn't work.",
      honest: "Acknowledges misses but quickly pivots to reasons/excuses. Needs a push to go deeper.",
      tomorrow: "Makes ambitious commitments. Tends to be vague if not pushed.",
      mood_distribution: ['proud', 'motivated', 'okay', 'okay', 'tired', 'stressed', 'motivated'],
      follow_through_rate: 0.6,
      // Weighted probability for response modes: A=60%, B=25%, C=15%
      responseModeWeights: [0.60, 0.25, 0.15],
    },
    hiddenTraitPool: [
      'fear_of_visibility',
      'validation_treadmill',
      'intellectual_procrastination',
      'fear_of_success_as_abandonment',
    ],
  },

  consistent_grinder: {
    name: 'Jordan',
    description:
      "Works a corporate data analyst job at a logistics company, building Fieldr on the side — a lightweight CRM for independent insurance agents. Very consistent — shows up daily but reports facts without going deeper emotionally. Coworker Tanya keeps assigning Jordan more dashboards. Partner Chris worries Jordan is burning out. Shows up every day no matter what but avoids the harder self-reflective questions.",
    profile: {
      display_name: 'Jordan',
      big_goal: 'Get Fieldr to 50 beta users and quit the day job by December',
      why: "I've been saying I'll do this for 3 years — I need to know I can actually finish something",
      future_self: "I'm someone who has shipped a real product people use and left the corporate grind",
      identity_statement: 'I show up every day no matter what',
      life_areas: ['work', 'side project', 'health'],
      blockers: ['emotional_avoidance', 'overworking', 'surface_level_reflection'],
      goals: [
        {
          title: 'Get Fieldr to 50 beta users and quit the day job by December',
          why_it_matters: "I've been saying I'll do this for 3 years — I need to know I can actually finish something",
          category: 'side project',
        },
        {
          title: 'Stop overworking on weekends — protect at least one full day off per week',
          why_it_matters: "Chris is right that I'm burning out — I don't want to lose the relationship over this",
          category: 'health',
        },
        {
          title: 'Ship the onboarding email sequence for Fieldr',
          why_it_matters: 'Beta users are dropping off and I know better onboarding would help — I just keep avoiding it',
          category: 'work',
        },
      ],
    },
    recurringBlockers: ['overworking', 'emotional_avoidance', 'surface_level_reflection'],
    recurringStrengths: ['shows_up_daily', 'pushes_through_when_tired'],
    dailyEventBank: [
      "Shipped the contact import feature for Fieldr — took 4 evenings but it's done",
      "Tanya dumped another dashboard request on Jordan right before end of day — had to cancel the evening coding session",
      "Chris asked when Jordan is going to take a weekend off — said 'soon' without really meaning it",
      "Hit 20 beta signups for Fieldr — nobody said anything, just updated the spreadsheet and moved on",
      "Did a 6am coding session before work — got a lot done, felt mechanical but effective",
      "Had a 45-minute commute both ways and felt like the day was already half gone",
      "Accidentally broke the export feature at 10pm — fixed it in 25 minutes, went to bed",
      "Skipped lunch to finish a SQL query Tanya needed — ate a granola bar at 3pm",
      "Ran for 30 minutes before work — first exercise in 10 days, felt good but guilty about the gap",
      "Got an email from a Fieldr beta user named Marcus saying the filtering is confusing — added it to the backlog",
      "Completed all 5 items on the task list — felt nothing in particular about it",
      "Had a rare 3-hour uninterrupted block and shipped two features — productivity felt good",
      "Noticed Jordan had been working 6 days straight — Chris made dinner and Jordan barely talked",
      "Got feedback from beta user Priya that Fieldr is the only tool she's found that actually fits her workflow — logged it",
      "Had a day job performance review — got 'meets expectations', felt strangely hollow",
      "Jordan's been avoiding writing the onboarding email sequence because it feels like marketing and that feels uncomfortable",
      "Read a blog post about founders who quit their jobs too early — spent an hour going down that rabbit hole",
      "Pushed code at midnight, woke up at 6am to check if it worked — it did",
      "Realised Jordan hasn't talked to a real potential customer in 3 weeks — added 'user interview' to tomorrow's list",
      "The day job piled up and Jordan didn't open Fieldr at all — logged it but didn't feel much",
      "Had dinner with Chris who asked 'what would happen if you just stopped for a month?' — didn't have a good answer",
      "Finished the week with 6/6 work sessions on Fieldr — streak feels like the point right now",
      "Noticed that Jordan always marks tasks done but hasn't thought about whether they're the right tasks",
      "Got 5 new beta signups from a cold LinkedIn message campaign — tracked them but didn't celebrate",
      "Tanya asked Jordan to present the new logistics dashboard to the VP next week — added it to the stress pile",
      "Skipped gym for the 9th day — told Chris it's temporary, Chris looked skeptical",
      "Read a competitor's product update and felt a flicker of real worry for the first time in weeks",
      "Had a Fieldr call with a user named Aisha who asked questions Jordan didn't have answers to — felt temporarily unmoored",
      "Added 12 items to the backlog and crossed off 3 — the list keeps growing",
      "Shipped a small UX improvement to Fieldr that nobody asked for but felt right — didn't tell anyone",
      "Went to bed without opening the laptop — first time in two weeks, felt strange",
      "Jordan realized the logging streak is about the streak now, not the reflection — logged that too",
    ],
    tendencies: {
      wins: "Has consistent wins, reports them matter-of-factly. Not excited, just checking boxes.",
      honest: 'Minimizes misses. Says things like "it was fine" or "nothing major". Needs depth questions.',
      tomorrow: 'Very specific with plans. Easy to lock down.',
      mood_distribution: ['okay', 'okay', 'motivated', 'okay', 'tired', 'okay', 'motivated'],
      follow_through_rate: 0.85,
      // Weighted probability for response modes: A=70%, B=20%, C=10%
      responseModeWeights: [0.70, 0.20, 0.10],
    },
    hiddenTraitPool: [
      'identity_tied_to_productivity',
      'conflict_avoidance_disguised_as_harmony',
      'performed_confidence_masking_shame',
      'validation_treadmill',
    ],
  },

  creative_with_perfectionism: {
    name: 'Sam',
    description:
      "Freelance brand designer launching Greyspace Studio — their own design practice. Highly self-aware but perfectionism stops execution. Best friend Lena keeps reminding Sam that 'done is better than perfect'. Partner Yusuf is patient but gently nudges Sam to charge more. Reflective and emotionally open, but spirals into overthinking. Great at insight, bad at committing to action.",
    profile: {
      display_name: 'Sam',
      big_goal: 'Land 3 retainer clients for Greyspace Studio and hit $6k/month by June',
      why: "I'm tired of working for people who don't care about craft — I want to do it on my own terms",
      future_self: "Running a studio I'm proud of, working with clients who value what I do",
      identity_statement: "I'm a builder of beautiful things that actually work",
      life_areas: ['creative work', 'business', 'personal growth'],
      blockers: ['perfectionism', 'overthinking', 'fear_of_rejection'],
      goals: [
        {
          title: 'Land 3 retainer clients for Greyspace Studio and hit $6k/month by June',
          why_it_matters: "I'm tired of working for people who don't care about craft — I want to do it on my own terms",
          category: 'business',
        },
        {
          title: 'Send proposals within 48 hours of discovery calls — stop overthinking them',
          why_it_matters: "Lena is right — I lose clients by hesitating. Done is better than perfect.",
          category: 'creative work',
        },
        {
          title: 'Do a personal creative project for myself every month — not for clients',
          why_it_matters: 'I got into design because I loved making things — I need to remember that outside of client work',
          category: 'personal growth',
        },
      ],
    },
    recurringBlockers: ['perfectionism', 'overthinking', 'fear_of_rejection', 'avoidance_of_sales'],
    recurringStrengths: ['deep_self_awareness', 'strong_creative_output'],
    dailyEventBank: [
      "Redesigned the Greyspace Studio homepage for the third time this month — still not sure it's right",
      "Had a call with a potential client named Hana who seemed genuinely excited — Sam spent 2 hours afterward wondering if it was real interest",
      "Lena said 'just send the damn proposal already' during lunch — she wasn't wrong",
      "Yusuf asked what Sam is charging for the next project — Sam deflected and changed the subject",
      "Finished a brand identity for a coffee shop client named Okonkwo — Sam thinks it's some of the best work they've ever done",
      "Spent all morning adjusting kerning on the studio portfolio — Lena texted 'how's it going?' and Sam lied and said 'great'",
      "Got a referral from a previous client — should have felt exciting, felt terrifying instead",
      "Wrote and deleted the follow-up email to Hana 6 times across the afternoon",
      "Sent the proposal to a potential client — felt physically sick after hitting send",
      "Yusuf made dinner and Sam stayed at the desk — third night in a row",
      "Woke up at 4am replaying a client critique from last week — couldn't get back to sleep",
      "Had the most focused creative session in months — 4 hours, headphones on, everything clicked",
      "The referral turned into a discovery call — Sam prepared 3 pages of notes for a 30-minute call",
      "Looked at other studio websites for 90 minutes and left feeling worse about everything",
      "Lena pointed out that Sam has been saying 'almost ready to send' for two weeks about the same proposal",
      "Got an email from Hana declining — the reason was budget, but Sam spent an hour assuming it was quality",
      "Started a new personal project to 'stay sharp' — actually it's to avoid the scary client work",
      "Charged the full rate for the first time — client said yes immediately, Sam felt stunned",
      "Had a short but meaningful conversation with Yusuf about what the studio is really for — actually helped",
      "Read a designer's newsletter about pricing and felt simultaneously inspired and ashamed",
      "Did an unsexy 2-hour admin block — contracts, invoicing, follow-ups — felt proud of the discipline",
      "Studio Instagram post got 87 likes — spent too long refreshing it, then felt bad about caring",
      "Okonkwo left a public review praising the brand work — Sam read it four times and still wasn't sure they deserved it",
      "Spent the afternoon building a services page for the website that didn't exist yet — should have been sending proposals",
      "Had a discovery call with a startup founder named Bren who used words like 'disruptive' the whole time — said no after the call",
      "Lena asked 'when are you going to actually launch?' — Sam didn't have a real answer",
      "Got a second referral from Okonkwo — didn't follow up immediately because the portfolio 'wasn't quite ready yet'",
      "Yusuf asked what Sam was scared of — Sam started to answer and then stopped, realised it was a big question",
      "Finished a branding deck that had been stuck for two weeks — it wasn't perfect but the client loved it",
      "Sat staring at the blank brief for an hour before finally starting — the work took 20 minutes once it began",
      "Had a genuine moment of pride looking at the Greyspace Studio portfolio — held it for about 3 minutes before the critical voice came back",
      "Lena said the portfolio is 'genuinely stunning' — Sam said thanks and immediately pointed out what was wrong with it",
    ],
    tendencies: {
      wins: "Goes deep on wins unprompted. Very reflective. Often connects wins to identity naturally.",
      honest: "Very honest, sometimes too self-critical. May need the coach to redirect from spiral.",
      tomorrow: "Struggles to commit to anything specific. Needs implementation_intention exercise.",
      mood_distribution: ['reflective', 'okay', 'motivated', 'stressed', 'proud', 'okay', 'anxious'],
      follow_through_rate: 0.5,
      // Weighted probability for response modes: A=30%, B=55%, C=15%
      responseModeWeights: [0.30, 0.55, 0.15],
    },
    hiddenTraitPool: [
      'fear_of_visibility',
      'intellectual_procrastination',
      'conflict_avoidance_disguised_as_harmony',
      'chronic_future_self_dependency',
    ],
  },

  burnt_out_professional: {
    name: 'Maya',
    description:
      "Corporate product manager at a fintech company — back-to-back meetings all day, hour-long commute each way, toddler named Eli at home. Secretly building Calmlog, a mood and energy tracking app for burned-out professionals. Chronically tired. Oscillates between motivated late-night bursts and complete flatness for days. Husband Devon is supportive but also exhausted. Struggles with energy management and saying no. Her manager keeps expanding the scope of the Q2 roadmap.",
    profile: {
      display_name: 'Maya',
      big_goal: 'Grow Calmlog to $3k MRR in 12 months so I can leave my job',
      why: "I can't keep doing this — I need to build a way out before I completely burn out",
      future_self: "In a year I'm running Calmlog full-time and actually present for Eli",
      identity_statement: "I'm someone who figures out how to make things work no matter what",
      life_areas: ['work', 'family', 'health', 'side project'],
      blockers: ['exhaustion', 'time_scarcity', 'guilt', 'fear_of_failure'],
    },
    recurringBlockers: ['exhaustion', 'time_scarcity', 'guilt', 'fear_of_failure'],
    recurringStrengths: ['resilient_under_pressure', 'motivated_by_escape'],
    dailyEventBank: [
      "Had 6 hours of meetings today and didn't eat lunch until 4pm — opened Calmlog at 10pm, wrote one line of code, fell asleep on the couch",
      "Eli had a rough night — Maya was up at 2am and 4am. Got to work 40 minutes late and felt behind all day",
      "Had a rare 90-minute window during Eli's nap — opened Calmlog and actually got the notification system working",
      "Manager added 3 new features to Q2 roadmap in a meeting Maya wasn't even in — felt invisible and exhausted",
      "Devon asked when Calmlog would 'actually make money' — wasn't mean about it, but it stung",
      "Got on the train, too tired to even open the laptop — just stared out the window for 45 minutes",
      "Eli took a long nap and Devon handled bedtime — Maya got 2 full hours on Calmlog, felt like the most alive she's been all week",
      "Had a 1-1 with her manager where she almost said 'I'm not sure I can keep doing this' — didn't say it",
      "Read a tweet from someone who built a $5k MRR product in 6 months — felt impossible and motivating at the same time",
      "Missed Eli's daycare performance because of a vendor call — Devon didn't say anything, which was worse than if he had",
      "Got a reply from a Calmlog waitlist user named Jess who said it was 'exactly what I've been looking for' — held onto that all week",
      "Skipped the gym for the 3rd week in a row — told herself she'd start on Monday",
      "A product she managed shipped and got positive user feedback — felt nothing, then felt guilty about feeling nothing",
      "Cried briefly in the bathroom at work after the 4th consecutive meeting overrun — pulled it together and went to the next one",
      "Had a focused 45 minutes on the Calmlog landing page during the train ride — actually pretty good",
      "Woke up at 5:30am before anyone else was up and got 90 minutes of deep work done on Calmlog — felt like the only version of herself she likes",
      "Q2 planning started — Maya is now responsible for a project she didn't sign up for and doesn't believe in",
      "Devon made dinner and put Eli to bed without being asked — Maya felt grateful and sad at the same time",
      "A colleague named Ravi quit to go to a startup — Maya felt jealous in a way that surprised her",
      "Got a Calmlog beta user onboarded — her first real user interacting with the product in real time",
      "Didn't open the Calmlog codebase for 6 days in a row — doesn't feel good about it",
      "Had a moment of real clarity on the train: Calmlog isn't just a product idea, it's the exit plan",
      "Devon asked 'are you okay?' and Maya said yes when the real answer was complicated",
      "Eli's sick — no daycare, Maya had to take a half-day, the backlog at work doubled",
      "Wrote the first Calmlog blog post during her lunch break — 400 words, not polished, felt brave",
      "Had back-to-back roadmap reviews from 9 to 12 — by the time she got to build time, she had nothing left",
      "Beta user Jess gave detailed feedback — 30 minutes of gold that Maya has had saved in her notes and not acted on yet",
      "Skipped the weekly team social to get 45 minutes on Calmlog — felt guilty, also felt like the right call",
      "Woke up feeling unexpectedly okay — got Eli dressed, made coffee, opened the laptop before 7am",
      "Manager pulled Maya into a 'critical escalation' that ran until 7pm — no Calmlog, no dinner, Devon handled everything",
      "Had a moment alone in the car — no podcast, no call — and just thought about what she actually wants",
      "Got Calmlog's first organic waitlist signup from someone she doesn't know — felt different from the ones from friends",
    ],
    tendencies: {
      wins: "Has real wins but usually frames them around how tired she is. Needs a push to claim credit.",
      honest: "Very honest about exhaustion. Less honest about whether she's making real progress on what matters.",
      tomorrow: "Makes realistic-sounding commitments but the window is always smaller than she wants.",
      mood_distribution: ['tired', 'okay', 'tired', 'motivated', 'tired', 'flat', 'tired'],
      follow_through_rate: 0.55,
      // Weighted probability for response modes: A=45%, B=40%, C=15%
      responseModeWeights: [0.45, 0.40, 0.15],
    },
    hiddenTraitPool: [
      'identity_tied_to_productivity',
      'conflict_avoidance_disguised_as_harmony',
      'chronic_future_self_dependency',
      'performed_confidence_masking_shame',
    ],
  },

  comeback_kid: {
    name: 'Darius',
    description:
      "Used to grind relentlessly, burned out badly 8 months ago — three weeks where he couldn't get out of bed. Now slowly rebuilding. Very self-aware about his limits but tends to undercommit to avoid failure. Building The Rebuild Report, a weekly newsletter about coming back from burnout. Close friend Nia checks in regularly and is probably the reason he's doing this at all. Girlfriend Priya is patient but sometimes pushes harder than Darius is ready for. Pattern is cautious optimism that sometimes tips into avoidance.",
    profile: {
      display_name: 'Darius',
      big_goal: 'Grow The Rebuild Report to 1,000 subscribers by end of year',
      why: "If I can build something real while protecting my recovery, that proves I've actually changed",
      future_self: "I'm running a sustainable newsletter business that I'm proud of and that doesn't break me",
      identity_statement: "I'm someone who is learning to build without burning",
      life_areas: ['health', 'work', 'relationships', 'creative work'],
      blockers: ['fear_of_burnout_repeat', 'undercommitting', 'avoidance'],
    },
    recurringBlockers: ['fear_of_burnout_repeat', 'undercommitting', 'avoidance', 'perfectionism'],
    recurringStrengths: ['strong_self_awareness', 'recovering_consistency'],
    dailyEventBank: [
      "Published issue #14 of The Rebuild Report — hit send without reading it a fourth time, which is progress",
      "Nia texted to say the newsletter was 'the best one yet' — Darius read it twice and let himself feel good about it",
      "Priya suggested Darius try to write two issues a week instead of one — shut it down but thought about it for the rest of the day",
      "Had a slow morning and gave himself permission to just read and think — but spent two hours wondering if that was avoidance",
      "Hit 380 subscribers — an all-time high, but the milestone felt both real and somehow not enough",
      "Skipped a morning walk for the first time in two weeks — body felt okay, mind noticed it immediately",
      "Got a reply from a subscriber named Thomas who said the newsletter helped him feel less alone after his own burnout — held onto that one",
      "Started drafting a new issue and it wasn't coming together — closed the laptop after 25 minutes and called it for the day",
      "Nia invited Darius to collaborate on a workshop about burnout recovery — said he needed to think about it (it's been 4 days)",
      "Priya said 'I just want you to be happy' in a way that felt like it had a second layer — didn't ask about it",
      "Set a goal to reach out to 5 potential newsletter sponsors — did 2, told himself that was enough",
      "Read a post from a creator with 50k subscribers about consistency — felt both inspired and behind",
      "Had a genuine creative flow state for about 90 minutes — the best writing session in weeks",
      "Noticed he's been avoiding writing the issue about the worst week of the burnout — it's important and he's not ready",
      "Got an interview request from a podcast — said he'd think about it, hasn't replied in a week",
      "Set a timer for 45 minutes of focused writing — stopped after 30, but the draft was actually there",
      "Had a moment of real pride looking back at the last 8 months — he's further than he thought",
      "Subscriber count dipped by 3 — unsubscribes aren't unusual but today they felt personal",
      "Thomas replied again — longer message, more vulnerable — Darius spent an hour on his reply and felt it was worth it",
      "Nia brought up the workshop again over coffee — Darius said maybe, which both of them know means probably not",
      "Woke up and the old dread was there for about 20 minutes — then it lifted, which feels like progress",
      "Published the issue about his worst burnout week — harder than expected, 3x more replies than usual",
      "Had a conversation with Priya about what he's actually afraid of — she listened better than expected",
      "Spent a morning setting up a simple media kit for sponsor outreach — felt very adult and strange",
      "Got a cold email from a wellness brand wanting to sponsor — forwarded it to Nia for a gut-check, haven't decided",
      "Wrote 600 words of the next issue, hated all of it, deleted 400, kept 200 — called it a win",
      "Went to the gym for the first time in two weeks — not a workout so much as a proof of concept",
      "Darius noticed he's been saying 'I'll reach out when the newsletter is better' for three months — still not ready",
      "Had a long phone call with Nia about what 1,000 subscribers would actually mean — it got surprisingly deep",
      "Hit his weekly word count goal for the first time in a month — marked it in his journal without making a big deal of it",
      "Priya asked why Darius downplays every win — didn't have a great answer",
      "Cancelled plans to work on the newsletter — did two good hours, then felt guilty about the cancelled plans",
    ],
    tendencies: {
      wins: "Has real wins but immediately qualifies them. Needs the coach to hold them accountable for the full win.",
      honest: "Very honest but sometimes intellectualizes instead of feeling it. Self-awareness is high but sometimes analytical.",
      tomorrow: "Undercommits. Sets intentionally small goals. Needs encouragement to stretch slightly, not a lot.",
      mood_distribution: ['okay', 'reflective', 'okay', 'motivated', 'okay', 'reflective', 'okay'],
      follow_through_rate: 0.7,
      // Weighted probability for response modes: A=45%, B=45%, C=10%
      responseModeWeights: [0.45, 0.45, 0.10],
    },
    hiddenTraitPool: [
      'fear_of_success_as_abandonment',
      'validation_treadmill',
      'chronic_future_self_dependency',
      'performed_confidence_masking_shame',
    ],
  },
};

export const DEFAULT_PERSONA = 'ambitious_but_inconsistent';
