-- Migration: 20260622_anon_auth_rls_fixes.sql
--
-- Hardens RLS policies now that anonymous authentication is enabled.
-- Anonymous users receive the `authenticated` role just like real users,
-- so every policy that relied on `USING (true)` or that allowed writes on
-- backend-only tables now needs explicit guards.
--
-- Two classes of problems are fixed:
--
--   1. "Service role manages X" policies with USING (true)
--      The backend APIs all use SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS
--      entirely by default.  These policies therefore served no legitimate
--      purpose while simultaneously granting every authenticated user
--      (including anonymous guests) unrestricted read/write/delete access to
--      ALL rows in those tables.  They are dropped here.
--
--   2. Backend-only tables with FOR ALL USING (auth.uid() = user_id)
--      The FOR ALL form lets the client INSERT rows as well as read them.
--      Anonymous users should not be able to read or write backend-generated
--      data (insights, progress events, causal extracts, etc.).  The policies
--      are replaced with ones that add:
--        AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
--
-- Tables intentionally left unchanged (anonymous guests need access):
--   reflection_sessions, reflection_messages, life_areas
--   (the guest campaign flow requires anonymous users to run full sessions)


-- ─── 1. Drop USING (true) "Service role" policies ───────────────────────────
-- Service role bypasses RLS; these policies only open holes for regular/anon users.

DROP POLICY IF EXISTS "Service role manages insights"            ON user_insights;
DROP POLICY IF EXISTS "Service role manages verification events" ON verification_events;
DROP POLICY IF EXISTS "Service role manages progress events"     ON user_progress_events;
DROP POLICY IF EXISTS "Service role manages commitment log"      ON goal_commitment_log;


-- ─── 2. user_insights ───────────────────────────────────────────────────────
-- Only real (non-anonymous) users should read their synthesised insights.

DROP POLICY IF EXISTS "Users can read their own insights" ON user_insights;
CREATE POLICY "Users can read their own insights"
  ON user_insights FOR SELECT
  USING (
    auth.uid() = user_id
    AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
  );


-- ─── 3. verification_events ─────────────────────────────────────────────────
-- Email verification is only relevant for real accounts, never anonymous guests.

DROP POLICY IF EXISTS "Users can read their own verification events" ON verification_events;
CREATE POLICY "Users can read their own verification events"
  ON verification_events FOR SELECT
  USING (
    auth.uid() = user_id
    AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
  );


-- ─── 4. user_progress_events ────────────────────────────────────────────────
-- Progress events are backend-generated and meaningful only for real users.

DROP POLICY IF EXISTS "Users can read their own progress events" ON user_progress_events;
CREATE POLICY "Users can read their own progress events"
  ON user_progress_events FOR SELECT
  USING (
    auth.uid() = user_id
    AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
  );


-- ─── 5. goal_commitment_log ─────────────────────────────────────────────────
-- Commitment tracking is only relevant once a user has a real account and goals.

DROP POLICY IF EXISTS "Users can read their own commitment log" ON goal_commitment_log;
CREATE POLICY "Users can read their own commitment log"
  ON goal_commitment_log FOR SELECT
  USING (
    auth.uid() = user_id
    AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
  );


-- ─── 6. follow_up_queue ─────────────────────────────────────────────────────
-- Coach follow-ups are generated by the backend and are only relevant for real
-- users.  The previous FOR ALL policy also allowed anonymous users to INSERT
-- rows, which is unintended.

DROP POLICY IF EXISTS "Users can manage their own follow_up_queue" ON follow_up_queue;
CREATE POLICY "Users can manage their own follow_up_queue"
  ON follow_up_queue FOR ALL
  USING (
    auth.uid() = user_id
    AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
  );


-- ─── 7. growth_markers ──────────────────────────────────────────────────────
-- Growth markers are backend-generated and only meaningful for real users.

DROP POLICY IF EXISTS "Users can manage their own growth_markers" ON growth_markers;
CREATE POLICY "Users can manage their own growth_markers"
  ON growth_markers FOR ALL
  USING (
    auth.uid() = user_id
    AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
  );


-- ─── 8. session_causal_extracts ─────────────────────────────────────────────
-- Causal extracts are synthesised by the backend; anonymous users should not
-- be able to insert or read these rows.

DROP POLICY IF EXISTS "Users can manage their own causal extracts" ON session_causal_extracts;
CREATE POLICY "Users can manage their own causal extracts"
  ON session_causal_extracts FOR ALL
  USING (
    auth.uid() = user_id
    AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
  );


-- ─── 9. session_thinking_events ─────────────────────────────────────────────
-- AI decision-event telemetry written exclusively by the backend; anonymous
-- users should not be able to read or write these rows.

DROP POLICY IF EXISTS "Users can manage their own session thinking events"
  ON session_thinking_events;
CREATE POLICY "Users can manage their own session thinking events"
  ON session_thinking_events FOR ALL
  USING (
    auth.uid() = user_id
    AND NOT coalesce((auth.jwt()->>'is_anonymous')::boolean, false)
  );
